### ISSUE TITLE
Create a json config file for apps 

### ISSUE THREAD

**Issue by Stelliance** [Stelliance/stelliance-widget#11]
Apps links (keycloak)
Companies logo links
By environment ?

**Comment by dajay** [comment]
[widget_app_config.csv](https://github.com/Stelliance/stelliance-widget/files/10344890/widget_app_config.csv)

**Comment by michaeldesigaud** [comment]
@louis-watrin Peux tu télécharger le fichier CSV et compléter le fichier [https://github.com/Stelliance/stelliance-widget/blob/main/src/assets/conf/widget-apps-conf.json](https://github.com/Stelliance/stelliance-widget/blob/main/src/assets/conf/widget-apps-conf.json) en conséquence ?

**Comment by louis-watrin** [comment]
ok

**Comment by louis-watrin** [comment]
Je mets aussi l'ap lemur-test?
Je laisse ofa ou pas?
